bootcoins:
  property: BootcoinsRate Profile Dev

server:
  port: 8080


spring:
  application:
    name: ms-bootcoins
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@clusterconexion.j8gyv.mongodb.net/?retryWrites=true&w=majority 
      database: bootcoins-db

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8088/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}