bootcoins:
  property: BootcoinsRate Profile Dev

spring:
  application:
    name: ms-bootcoins
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@clusterconexion.j8gyv.mongodb.net/?retryWrites=true&w=majority 
      database: bootcoins-db