server:
  port: 8089

kafka:
  topic:
    name: transaction-request
spring:
  kafka:
    bootstrap-server: localhost:9092
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8088/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}